### ISSUE TITLE
OER encoding: missing leading pad byte for the big positive integers without constraints

### ISSUE THREAD

**Issue by viktorTarasov** [eclipse/titan.core#129]
Here is logs from OER functional tests:

> Test case tc_OER_Int started.
dec_OER_Int(): Stream before decoding: '0500AAAAAAAA'O
dec_OER_Int(): Decoded integer: 2863311530
enc_OER_Int(): Encoding integer: 2863311530
enc_OER_Int(): Stream after encoding: '04AAAAAAAA'O

"It works for me" with the applied https://github.com/viktorTarasov/titan.core/commit/43798b0e5b98e18aebed57cad3b09115eb0c8fbf

**Comment by BotondBaranyi** [comment]
Hi,

thank you for your contribution!

It looks good, but the padding byte is only needed for signed integers. A ‘p_td.oer->signed_’ should be added to the conditions for adding the pad byte.

For example:
pad = p_td.oer->signed_ && !(bn_as_bin[0] & 0x80);
and
pad = p_td.oer->signed_ && (bn_as_bin[0] & 0x80);

It could also be checked later, when 'pad' is checked.

Best regards,
Botond Baranyi

**Comment by viktorTarasov** [comment]
Ok, thanks. I will update PR.

Probably the same issue:
I'm trying to encode big positive integer with variable length:

> Uint   ::= INTEGER (0..MAX)
> ...
> external function enc_OER_Uint(in Uint pdu) return octetstring with { extension "prototype(convert) encode(OER)" }
... 

And this integer is encoded as **Signed** one:

> enc_OER_Uint(): Encoding integer: 115307965754428812535861235258289182183752994114051557942764040435498874699501
enc_OER_Uint(): Stream after encoding: '2100FEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEED'O

I'll try to investigate and to understand it ...

**Comment by BotondBaranyi** [comment]
The signed check should fix this, too.

**Comment by viktorTarasov** [comment]
I've tried, but it seems that
_Uint ::= INTEGER (0..MAX)_
is not seen as unsigned.

Here are the test logs with _printf_ added into _Integer.cc_:

>enc_OER_Uint(): Encoding integer: 8234104123542484900769178205574010627627573691361805720124810878238590820080
Integer.cc +1839: INTEGER::OER_encode() Is signed? 1
enc_OER_Uint(): Stream after encoding: '20123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0'O
enc_OER_Uint(): Encoding integer: 115307965754428812535861235258289182183752994114051557942764040435498874699501
Integer.cc +1839: INTEGER::OER_encode() Is signed? 1
enc_OER_Uint(): Stream after encoding: '2100FEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEED'O

**Comment by BotondBaranyi** [comment]
There seems to be something wrong with the C++ code generation.
Uint's OER settings are not generated (it's treated as if it were a regular integer).
If it's used in a structure, then its settings are generated and the encoding works fine.

For example:
Seq ::= SEQUENCE {
  field Uint
}

{ field := 115307965754428812535861235258289182183752994114051557942764040435498874699501 }
is encoded into '20FEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEEDFEED'O.

I'm currently looking into this fault.

**Comment by viktorTarasov** [comment]
IMHO somewhere near https://github.com/eclipse/titan.core/blob/master/compiler2/Type_chk.cc#L3061
additional
_else  if (lower_inf && !upper_inf)_ 
could be solution.

As an exercise I've ventures to add the _non_empty_ member to _class OerAST_,
activate it in _Type::chk_oer()_ in the else-if above,
and add its check to _OerAST::empty()_ .
"For me it works."

Hope this will help.

**Comment by BotondBaranyi** [comment]
I've fixed the code generation issue:
https://github.com/eclipse/titan.core/commit/65010f8c68ebb52e4243921d6a1f4a043a6eff8a

As for the second part of your comment, I don't understand what you're trying to do...

**Comment by viktorTarasov** [comment]
Fine, thanks.
It works for encoding.

For decoding there is still an issue -- at
https://github.com/eclipse/titan.core/blob/master/core/Integer.cc#L1887 
the result of decoding is expected as negative, while the 'signed_' flag is at 'false'.

Sorry for the noise,
in my exercise I was trying to dissociate the condition _'p_td.oer->bytes == -1'_ 
from decision about  if the integer is (or expected to be) signed or not,
as it actually the case at L1887.

**Comment by viktorTarasov** [comment]
I've updated the initial PR, following your recommendations.
https://github.com/viktorTarasov/titan.core/commit/230d08a8ca772033bbe847072d53d4f29e951c37

**Comment by viktorTarasov** [comment]
I've updated once more this PR to add the fix of the decoding problem .
Now I can go through the all functional tests of  _INTEGER_ in different forms.
Not sure that there are no side effects for the future -- will continue with the functional tests of OER .

**Comment by BotondBaranyi** [comment]
Please create a pull request with this commit.

Here's a guide to help:
https://docs.google.com/presentation/d/1AVi3Be3qYmkYm6VEf4BnYHYa3hwpjjIM5EQc7W6LtNE/edit#slide=id.p

**Comment by viktorTarasov** [comment]
Pull request  #139 created.
